# Generated by Django 3.0.7 on 2020-08-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadacuanto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Regularidad',
            },
        ),
        migrations.CreateModel(
            name='cirugias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cirugia', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Cirugias',
            },
        ),
        migrations.CreateModel(
            name='controles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_control', models.CharField(max_length=50)),
                ('regularidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.cadacuanto')),
            ],
            options={
                'verbose_name_plural': 'Controles',
            },
        ),
        migrations.CreateModel(
            name='examene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=50)),
                ('tipo_examen', models.CharField(max_length=20)),
                ('especificaciones', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dosis', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('fecha_hospitalizacion', models.DateField()),
                ('num_ficha', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevision', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Previsiones',
            },
        ),
        migrations.CreateModel(
            name='profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=60)),
                ('profesion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='regimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regimen', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Regimenes',
            },
        ),
        migrations.CreateModel(
            name='tipo_reposo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Reposos',
            },
        ),
        migrations.CreateModel(
            name='recien_nacido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recien_nacido', models.CharField(max_length=50)),
                ('num_ficha', models.IntegerField()),
                ('rut', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.paciente')),
                ('prevision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.prevision')),
            ],
            options={
                'verbose_name_plural': 'Recien Nacidos',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.prevision'),
        ),
        migrations.CreateModel(
            name='hoja_indicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('examen', models.BooleanField(default=False)),
                ('alta', models.BooleanField(default=False)),
                ('Nombre_cirugias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.cirugias')),
                ('control', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.controles')),
                ('nombre_medicamento', models.ManyToManyField(blank=True, to='Maternidad.medicamentos')),
                ('nombre_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.paciente')),
                ('nombre_profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.profesional')),
                ('reposo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.tipo_reposo')),
                ('tipo_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maternidad.regimen')),
            ],
        ),
    ]
