# Generated by Django 3.0.7 on 2020-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maternidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='embarazada',
            field=models.BooleanField(default=False),
        ),
    ]
