# Generated by Django 3.0.7 on 2020-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maternidad', '0002_paciente_embarazada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='num_ficha',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_hospitalizacion',
            field=models.DateField(auto_now=True),
        ),
    ]
